# Generated by Django 5.2.8 on 2025-11-21 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaseosa',
            name='azucar',
        ),
        migrations.RemoveField(
            model_name='gaseosa',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='gaseosa',
            name='sabor',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='gaseosa',
            name='contenido_ml',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='gaseosa',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gaseosa',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gaseosa',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
