# Generated by Django 5.2.8 on 2025-11-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0004_remove_cliente_user_remove_gaseosa_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaseosa',
            name='sku',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
