# Generated by Django 5.2.8 on 2025-11-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0006_carritotemporal_gaseosa_presentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='perfil',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='identificador_telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
