# Generated by Django 5.2.8 on 2025-11-22 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0007_perfil_correo_perfil_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaseosa',
            name='contenido_ml',
        ),
        migrations.RemoveField(
            model_name='gaseosa',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='gaseosa',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='gaseosa',
            name='sku',
        ),
        migrations.AddField(
            model_name='gaseosa',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gaseosa',
            name='sku_base',
            field=models.CharField(default=0, help_text='Ejemplo: CO para Coca Cola, FAN para Fanta', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.CharField(max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=20, unique=True)),
                ('gaseosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='Distribebidas.gaseosa')),
            ],
        ),
    ]
