# Generated by Django 5.2.8 on 2025-11-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0008_remove_gaseosa_contenido_ml_remove_gaseosa_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaseosa',
            name='sku_base',
            field=models.CharField(help_text='Ejemplo: CO para Coca Cola, FAN para Fanta', max_length=10),
        ),
    ]
