# Generated by Django 5.2.8 on 2025-11-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0009_alter_gaseosa_sku_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaseosa',
            name='sku_base',
            field=models.CharField(help_text='Ejemplo: CO para Coca Cola, FAN para Fanta', max_length=10, unique=True),
        ),
    ]
