# Generated by Django 5.2.8 on 2025-11-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0010_alter_gaseosa_sku_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='sku',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='gaseosa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='Distribebidas.gaseosa'),
        ),
    ]
