# Generated by Django 5.2.8 on 2025-11-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0011_remove_inventario_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='contenido',
            field=models.CharField(choices=[('100ml', '100ml'), ('150ml', '150ml'), ('200ml', '200ml'), ('500ml', '500ml'), ('750ml', '750ml'), ('1L', '1L'), ('1.5L', '1.5L'), ('2L', '2L'), ('2.5L', '2.5L'), ('3L', '3L')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Presentacion',
        ),
    ]
