# Generated by Django 5.2.8 on 2025-11-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0012_inventario_contenido_delete_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='sku',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
