# Generated by Django 5.2.8 on 2025-11-22 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0013_alter_inventario_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='contenido',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='gaseosa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distribebidas.gaseosa'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distribebidas.pedido'),
        ),
    ]
