# Generated by Django 5.2.8 on 2025-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0015_factura_iva_alter_factura_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='iva',
        ),
        migrations.AddField(
            model_name='perfil',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='codigo_telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='correo',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
