# Generated by Django 5.2.8 on 2025-11-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0017_alter_perfil_correo_alter_perfil_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='codigo_telefono',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='pais_origen',
        ),
    ]
