# Generated by Django 5.2.8 on 2025-11-23 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0018_remove_perfil_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Distribebidas.inventario'),
        ),
    ]
