# Generated by Django 5.2.8 on 2025-11-24 15:08

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0019_itempedido_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('procesado', 'Procesado'), ('cancelado', 'Cancelado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nacionalidad',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
