# Generated by Django 5.2.15 on 2026-06-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Distribebidas', '0020_inventario_imagen_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('gaseosa', 'contenido')},
        ),
    ]
